### ISSUE TITLE
Mocking S3.upload

### ISSUE THREAD

**Issue by marceloavf** [mapbox/aws-sdk-jest#1]
Hi,

I was wondering, can I use this to spy on upload function?

Thanks.

**Comment by marceloavf** [comment]
I tested it and it work, but I'm having problem with request events, do you have any example of how to mock those responses?

**Comment by rclark** [comment]
There's a bullet at the very bottom of the readme:

> You should be familiar with the AWS.Request object, because if your code needs to set special expectations for .promise(), .eachPage(), or .on(), then you're going to have to use AWS.spyOn() and provide your own implementations for those Request methods.

[SDK docs about the request object](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Request.html). To mock the request events, you might have to make your own [EventEmitter](https://nodejs.org/api/events.html#events_class_eventemitter).
