### ISSUE TITLE
spyOnPromise mock not cleared for nested clients

### ISSUE THREAD

**Issue by drboyer** [mapbox/aws-sdk-jest#2]
I noticed that when using a nested client like `DynamoDB.DocumentClient`, `spyOnPromise()` mocks are not cleared correctly. The first mock will work as expected, but any subsequent attempts to mock will result in `DynamoDB.DocumentClient.<METHOD> is already mocked` errors.

Curiously, even calling `jest.clearAllMocks()`, either within the test or `afterEach()` does not clear the mocks.

I've provided an example of this behavior in this public repository: https://github.com/drboyer/ddb-document-mock

/cc: @rclark

**Comment by rclark** [comment]
https://github.com/mapbox/aws-sdk-jest/blob/6e616a79fcc5ceff5e687e637b9ff776398ba2dd/test/mock.test.js#L138-L151

Can you tell what it is about this test that's not catching the behavior that you're seeing?

**Comment by drboyer** [comment]
Yep, Lines 148-150 in the snippet you posted assert that a new DocumentClient (`ddb`) is not mocked, but do not attempt to then re-mock the the same method. The test will fail if the following is added to the test block:

https://github.com/mapbox/aws-sdk-jest/blob/0514d9e932f1ba46e99fd7de26528d914fea2839/test/mock.test.js#L152-L158

For comparison, you can clear and reset a non-nested mock in the same test block with no issue (this test passes):

https://github.com/mapbox/aws-sdk-jest/blob/a69fc441ca1b69d622684c9f18b5affb02233d1d/test/mock.test.js#L40-L54

(Lines 51-53 were added here)

You can try these for yourself in the [drboyer-nested-mock branch](https://github.com/mapbox/aws-sdk-jest/tree/drboyer-nested-mock)
